### ISSUE TITLE
CSS syntax coloring fails for 'justify-items' property, missing scope.

### ISSUE THREAD

**Issue by aeschli** [atom/language-css#137] opened 2018-02-05 11:41 UTC
1. Write a `justify-items` property on any selector of a CSS file, for instance:

```
div {
    justify-items: stretch;
}
```

2. Verify that the property name `justify-items` is not being colored like a property name.

3. Verify using the TM scope inspector that, unlike other CSS property names, the token for `justify-items` doesn't have the **support.type.property-name.css** scope.

![screenshot_3](https://user-images.githubusercontent.com/5291103/35750876-3e5d245a-0835-11e8-9771-e60293daa829.png)
![screenshot_4](https://user-images.githubusercontent.com/5291103/35750880-3ebdb23e-0835-11e8-803f-458b86fecfff.png)

_Copied from original issue: Microsoft/vscode#42843_

**Comment by 50Wliu** [comment] 2018-02-05 13:16
Duplicate of #131

**Closed by 50Wliu** 2018-02-05 13:16 UTC

**Comment by cleanenergyjoy** [comment] 2018-02-05 15:16
Cleanenergyjoy@gmail.com
